# the next two lines are optional
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello again
    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch name is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Hello world action step
        id: hello
        uses: AllanPedaIPG/hello-world-docker-action@v1
        with:
          who-to-greet: 'Allan at interpublic.com'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
